### ISSUE TITLE
一直报错。

### ISSUE THREAD

**Issue by z244370114** [Zzz468005600/Stone#2]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lokhttp3/Address;
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by Zzz468005600** [comment]
修复了。。。
