### ISSUE TITLE
帮忙解答一下，在网上查了很多办法也没有解决；

### ISSUE THREAD

**Issue by BeEagle** [Zzz468005600/Stone#3]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lokhttp3/Address;

**Comment by Zzz468005600** [comment]
一年多过去了，不知道朋友是否解决了这个问题。。。
好久没更新这个代码了，刚把一些问题修复了
